# These are supported funding model platforms

github: DannyDorito # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
ko_fi: johnallis0n # Replace with a single Ko-fi username
custom: https://paypal.me/johnallis0n
